server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.232.178
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli_cart?serverTimezone=GMT%2B8
  task:
    #spring执行器配置，对应TaskExecutionProperties配置类，对于spring异步任务，会使用该执行器
    execution:
      thread-name-prefix: task- #线程池的线程名前缀，默认是task-，建议根据自己的应用名配置
      pool:
        core-size: 8 #核心线程数，线程池初始化时的线程数，默认为8
        max-size: 20 #最大线程数，只有当缓冲队列满了之后，才会申请超过核心线程数的线程，默认为Integer.MAX.VALUE
        keep-alive: 60s #允许线程的空闲时间，当线程空闲时间达到该值会销毁线程，默认为60s
        queue-capacity: 200 #缓冲队列的大小
        allow-core-thread-timeout: true #是否允许核心线程超时，即开启线程池的动态增长和缩小
      shutdown:
        await-termination: true #当应用关闭时，是否等待定时任务执行结束，默认为false，建议设置为true
        await-termination-period: 60 #等待任务完成的最大时长，单位为秒，默认为0
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
jwt:
  pubKeyPath: D:\Sgg\rsa\rsa.pub
  userKey: user-key
  expire: 15552000
  cookieName: GMALL-TOKEN

